fint:
 adapter:
  organizations: fint.health
  sse-endpoint: https://play-with-fint-adapter.felleskomponent.no/provider/sse/%s
  status-endpoint: https://play-with-fint-adapter.felleskomponent.no/provider/status
  response-endpoint: https://play-with-fint-adapter.felleskomponent.no/provider/response

